connectors:
  matrix:
    # Required
    mxid:  #id goes here. bot_{funⅽtionaⅼity_of_the_bot}
    password: #password goes here. 
    rooms:
      'main': '#gp18-test:nitro.chat'
    enable_encryption: True
    # Optional
    homeserver: "https://nitro.chat"
    nick: "NLP_HW2_18"  # The nick will be set on startup

skills:
  - name: help
    path: chatbot/skills/help_skill.py

  - name: accept_invite
    path: chatbot/skills/accept_invite.py

  - name: extractor
    path: chatbot/skills/extractor.py